### ISSUE TITLE
Database Exception при поиске в категории

### ISSUE THREAD

**Issue by loveorigami** [webadmin87/rzwebsys7#25]
Нарвался на ошибку.
* Настройки у меня на MySql
* Сделал главное меню (main)
* Добавил child -> hello
Через быстрый поиск пытаюсь найти такой элемент меню, который спрятан во втором уровне..
получаю
![1111](https://cloud.githubusercontent.com/assets/98164/8163241/9e4d7c04-138a-11e5-890c-4c24dedbacaf.jpg)
```php 
//в дебагере
exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~* 'hello')' at line 1' in X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Command.php:825 Stack trace: 
#0 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Command.php(825): PDOStatement->execute() 
#1 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Command.php(375): yii\db\Command->queryInternal('fetchColumn', 0) 
#2 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Query.php(389): yii\db\Command->queryScalar() 
#3 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Query.php(296): yii\db\Query->queryScalar('COUNT(*)', NULL) 
#4 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\ActiveDataProvider.php(165): yii\db\Query->count('*', NULL) #5 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(147): yii\data\ActiveDataProvider->prepareTotalCount() 
#6 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\ActiveDataProvider.php(105): yii\data\BaseDataProvider->getTotalCount() 
#7 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(79): yii\data\ActiveDataProvider->prepareModels() 
#8 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(92): yii\data\BaseDataProvider->prepare() 
#9 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(133): yii\data\BaseDataProvider->getModels() 
#10 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(178): yii\data\BaseDataProvider->getCount() 
#11 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(149): yii\widgets\BaseListView->renderSummary() 
#12 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\grid\GridView.php(307): yii\widgets\BaseListView->renderSection('{summary}') 
#13 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(126): yii\grid\GridView->renderSection('{summary}') #14 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #15 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(129): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') #16 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\grid\GridView.php(282): yii\widgets\BaseListView->run() #17 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(97): yii\grid\GridView->run() #18 X:\domains\_dev\rzweb.yii\common\widgets\admin\views\grid.php(25): yii\base\Widget::widget(Array) #19 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #20 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #21 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, Object(common\widgets\admin\Grid)) #22 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(187): yii\base\View->render('grid', Array, Object(common\widgets\admin\Grid)) #23 X:\domains\_dev\rzweb.yii\common\widgets\admin\Grid.php(163): yii\base\Widget->render('grid', Array) #24 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(97): common\widgets\admin\Grid->run() #25 X:\domains\_dev\rzweb.yii\app\modules\news\modules\admin\views\news-section\_grid.php(22): yii\base\Widget::widget(Array) #26 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #27 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #28 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, NULL) #29 X:\domains\_dev\rzweb.yii\app\modules\news\modules\admin\views\news-section\index.php(40): yii\base\View->render('_grid', Array) #30 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #31 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #32 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, Object(app\modules\news\modules\admin\controllers\NewsSectionController)) #33 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Controller.php(371): yii\base\View->render('index', Array, Object(app\modules\news\modules\admin\controllers\NewsSectionController)) #34 X:\domains\_dev\rzweb.yii\common\actions\crud\Base.php(88): yii\base\Controller->render('index', Array) #35 X:\domains\_dev\rzweb.yii\common\actions\crud\TAdmin.php(52): common\actions\crud\Base->render('index', Array) #36 [internal function]: common\actions\crud\TAdmin->run(1) #37 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array) #38 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array) #39 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('index', Array) #40 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('news/admin/news...', Array) #41 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) #42 X:\domains\_dev\rzweb.yii\app\web\index.php(23): yii\base\Application->run() #43 {main} Next exception 'yii\db\Exception' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~* 'hello')' at line 1 The SQL being executed was: SELECT COUNT(*) FROM `news_sections` WHERE ((`lft` > 1) AND (`rgt` < 6) AND (`level` <= 2)) AND (`news_sections`.`title` ~* 'hello')' in X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Schema.php:595 Stack trace: #0 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Command.php(840): yii\db\Schema->convertException(Object(PDOException), 'SELECT COUNT(*)...') #1 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Command.php(375): yii\db\Command->queryInternal('fetchColumn', 0) #2 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Query.php(389): yii\db\Command->queryScalar() #3 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\db\Query.php(296): yii\db\Query->queryScalar('COUNT(*)', NULL) #4 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\ActiveDataProvider.php(165): yii\db\Query->count('*', NULL) #5 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(147): yii\data\ActiveDataProvider->prepareTotalCount() #6 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\ActiveDataProvider.php(105): yii\data\BaseDataProvider->getTotalCount() #7 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(79): yii\data\ActiveDataProvider->prepareModels() #8 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(92): yii\data\BaseDataProvider->prepare() #9 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\data\BaseDataProvider.php(133): yii\data\BaseDataProvider->getModels() #10 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(178): yii\data\BaseDataProvider->getCount() #11 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(149): yii\widgets\BaseListView->renderSummary() #12 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\grid\GridView.php(307): yii\widgets\BaseListView->renderSection('{summary}') #13 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(126): yii\grid\GridView->renderSection('{summary}') #14 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array) #15 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\widgets\BaseListView.php(129): preg_replace_callback('/{\\w+}/', Object(Closure), '{summary}\n{item...') #16 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\grid\GridView.php(282): yii\widgets\BaseListView->run() #17 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(97): yii\grid\GridView->run() #18 X:\domains\_dev\rzweb.yii\common\widgets\admin\views\grid.php(25): yii\base\Widget::widget(Array) #19 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #20 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #21 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, Object(common\widgets\admin\Grid)) #22 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(187): yii\base\View->render('grid', Array, Object(common\widgets\admin\Grid)) #23 X:\domains\_dev\rzweb.yii\common\widgets\admin\Grid.php(163): yii\base\Widget->render('grid', Array) #24 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Widget.php(97): common\widgets\admin\Grid->run() #25 X:\domains\_dev\rzweb.yii\app\modules\news\modules\admin\views\news-section\_grid.php(22): yii\base\Widget::widget(Array) #26 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #27 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #28 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, NULL) #29 X:\domains\_dev\rzweb.yii\app\modules\news\modules\admin\views\news-section\index.php(40): yii\base\View->render('_grid', Array) #30 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(325): require('X:\\domains\\_dev...') #31 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile('X:\\domains\\_dev...', Array) #32 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\View.php(149): yii\base\View->renderFile('X:\\domains\\_dev...', Array, Object(app\modules\news\modules\admin\controllers\NewsSectionController)) #33 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Controller.php(371): yii\base\View->render('index', Array, Object(app\modules\news\modules\admin\controllers\NewsSectionController)) #34 X:\domains\_dev\rzweb.yii\common\actions\crud\Base.php(88): yii\base\Controller->render('index', Array) #35 X:\domains\_dev\rzweb.yii\common\actions\crud\TAdmin.php(52): common\actions\crud\Base->render('index', Array) #36 [internal function]: common\actions\crud\TAdmin->run(1) #37 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Action.php(92): call_user_func_array(Array, Array) #38 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\Action->runWithParams(Array) #39 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('index', Array) #40 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\web\Application.php(84): yii\base\Module->runAction('news/admin/news...', Array) 
#41 X:\domains\_dev\rzweb.yii\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request)) 
#42 X:\domains\_dev\rzweb.yii\app\web\index.php(23): yii\base\Application->run() 
#43 {main} Additional Information: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~* 'hello')' at line 1 )
```

**Comment by webadmin87** [comment]
Система разрабатывалась на PostgreSql и с MySql не тестировалась. Вероятно где то могут быть использованы операторы и конструкции не поддерживаемые MySql.
В данном случае к exception приводит оператор сопоставления с регулярным выражением ( ~* ). Его приходится использовать так как в Postgresql оператор like регистрозависимый, что не очень удобно.
